package loader

// Credits preserves the production credits shown before each screen.
var credits = map[string][]string{
	"beatdis":    {"                    ", "                    ", " TCB BEAT DIS DEMO       ", "                         ", "PROGRAM BY NICK,JAS      ", "   GRAPHICS BY ES        ", "       FONT BY           ", "NICK'S PC-FONT-MAKER     ", "                         ", "  SAMPLED SOUND BY       ", "      AN  COOL           ", "                         ", " SOUNDCHIP-SOUND BY      ", "     MAED MAEX           ", "COMPOSED BY F. GRAY      ", "                         ", " PLEASE WAIT WHILE       ", "   DECOMPRESSING         ", "                    ", "                    ", "                    ", "                    ", "                    "},
	"delta":      {"                    ", "                    ", "       THE         ", "    DELTA FORCE    ", "     MEGA-DEMO     ", " (SPHERICOOL DEMO) ", "                   ", "PROGRAM BY NEW MODE", " GRAPHICS BY SLIME ", "   AND  QUESTLORD  ", "THE SHIT BUBBLES BY", "         ES        ", "                   ", "  SOUND BY ZZZ MAX ", "    COMPOSED BY    ", "   HOBB  RUBBARD   ", "                   ", "                   ", " PLEASE WAIT WHILE ", "   DECOMPRESSING   ", "                    ", "                    ", "                    "},
	"tnt3":       {"                    ", "                    ", "       THE        ", "     TNT-CREW     ", "   VECTOR-SCREEN  ", "                  ", "PROGRAM BY HEXADEZ", "     AND JOJO     ", "                  ", " SOUND BY NAP MAX ", "   COMPOSED  BY   ", "   DON'T ASK ME   ", "                  ", "                  ", "                  ", "PLEASE WAIT WHILE ", "  DECOMPRESSING   ", "                   ", "                   ", "                   ", "                    ", "                    ", "                    "},
	"wow":        {"                    ", "                    ", " TCB WOW!-SCROLLER ", "                   ", "PROGRAM BY NICK,JAS", "   GRAPHICS BY ES  ", "                   ", "  SAMPLED SOUND BY ", "      AN  COOL     ", "                   ", " PLEASE WAIT WHILE ", "   DECOMPRESSING   ", "                   ", "                   ", "                   ", "                   ", "                   ", "                   ", "                    ", "                    ", "                    ", "                    ", "                    "},
	"hidden":     {"                    ", "        TEX         ", " THE HIDDEN SCREEN  ", "                    ", "THE RUMOURS ABOUT AN", "ST-SOUNDTRACKER ARE ", "TRUE, SEE SCROLLTEXT", "LISTEN TO THE FIRST ", "   SONG DONE WITH   ", " THE SAMPLE-MON ST  ", "                    ", " MOVE THE MOUSE !!! ", "                    ", "  PROGRAM  BY 6719  ", " GRAPHIX BY HEXAGON ", "     MICE BY ES     ", "  COMPOSITION  AND  ", "      SOUND BY      ", " MAD (FEED ME) MAX  ", "                    ", "PLEASE WAIT A MOMENT", "    SLEEP-MODE...   ", "                    "},
	"starballs":  {"                    ", "                    ", " TNT-CREW STARBALLS", "                   ", " PROGRAM BY HEXOGEN", "   GRAPHICS BY ES  ", "                   ", "      SOUND BY     ", "    MAX THE HAIRY  ", "     COMPOSED BY   ", "  ROBB THE HUBBARD ", "                   ", " TRY THE KEYS 1...0", "                   ", " PLEASE WAIT WHILE ", "   DECOMPRESSING   ", "                   ", "                   ", "                   ", "                   ", "                    ", "                    ", "                    "},
	"replicants": {"                    ", "                    ", "   THE REPLICANTS   ", "   WOBBLY SPRITES   ", "                    ", "PROGRAM BY EXCALIBUR", "    GRAPHICS  BY    ", "     RANK XEROX     ", "                    ", "  SOUND BY BIG MAX  ", "     COMPOSED BY    ", "     JEROEN  TEL    ", "                    ", "  USE JOYSTICK TO   ", " CONTROL SCROLLING  ", "                    ", " PLEASE WAIT WHILE  ", "   DECOMPRESSING    ", "                    ", "                    ", "                    ", "                    ", "                    "},
	"tnt2":       {"                    ", "                    ", "      TNT-CREW      ", "   SUPERSCROLLER    ", "                    ", " PROGRAM BY HEXOGEN ", "   GRAPHICS BY ES   ", "                    ", "SOUND BY MAD AND MAX", "     COMPOSED BY    ", "     JEROEN  TEL    ", "                    ", " TRY THE KEYS 1..4  ", "AND CRSR LEFT/RIGHT ", "                    ", " PLEASE WAIT WHILE  ", "   DECOMPRESSING    ", "                   ", "                   ", "                   ", "                    ", "                    ", "                    "},
	"level16":    {"                    ", "                    ", "LEVEL 16 FULLSCREEN ", "                    ", "  PROGRAM BY ILJA   ", "  GRAPHICS BY DON   ", " SOUND  BY MAD MAX  ", "COMPOSED BY MAD MAX ", "                    ", "SPECIAL THANX TO JAN", "AND STEPHANE FOR THE", "      F O N T       ", "    ONE BUBBLE      ", "AND !%&%$/(&) BY ES ", "                    ", " PLEASE WAIT WHILE  ", "   DECOMPRESSING    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    "},
	"multiplane": {"                    ", "                    ", "       TCB'S        ", " SUPER-MULTIPLANE-  ", " 3D-SINE-DISTORTED- ", "  AND-WHOLE-LOTTA-  ", "THINGS-MORE-SCROLLER", "                    ", "PROGRAM AND GRAPHIX ", "      BY NICK       ", "                    ", "SOUND BY MAX,THE MAD", "  COMPOSED BY ROBB  ", "                    ", "                    ", " PLEASE WAIT WHILE  ", "   DECOMPRESSING    ", "                   ", "                   ", "                   ", "                    ", "                    ", "                    "},
	"diskcopier": {"                     ", "                     ", " TEX : COPY-PROGRAM  ", "                     ", " PROGRAM  BY 6719    ", "         AND MAD MAX ", " GRAPHIX  BY ES      ", " SOUND    BY MAH MAH ", "     COMPOSED BY     ", "     JEROEN  TEL     ", "                     ", "PRESS SPACE TO START ", "   OR '0' TO EXIT    ", "                     ", "                     ", "PLEASE WAIT A MOMENT ", "    SLEEP-MODE...    ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     "},
}
